package com.wmserp.app.domain.common

/**
 * Stable identifiers for errors produced by the app itself (as opposed to free-text messages
 * returned by ERPNext). The presentation layer maps these to localized strings; [AppError.message]
 * always carries an English fallback so logs and tests stay readable.
 */
enum class ErrorCode {
    INVALID_URL,
    USERNAME_REQUIRED,
    PASSWORD_REQUIRED,
    API_TOKEN_REQUIRED,
    INVALID_CREDENTIALS,
    INVALID_API_TOKEN,
    NO_SESSION_COOKIE,
    CURRENT_PASSWORD_REQUIRED,
    PASSWORD_TOO_SHORT,
    PASSWORDS_DO_NOT_MATCH,
    PASSWORD_UNCHANGED,
    CURRENT_PASSWORD_INCORRECT,
    FIRST_NAME_REQUIRED,
    ITEM_REQUIRED,
    QTY_MUST_BE_POSITIVE,
    WAREHOUSES_REQUIRED,
    WAREHOUSES_MUST_DIFFER,
    TARGET_WAREHOUSE_REQUIRED,
    SOURCE_WAREHOUSE_REQUIRED,
    UNKNOWN_ORDER_ROW,
    OVER_RECEIVE,
    OVER_DISPATCH,
    SELECT_WAREHOUSE_FOR_ITEM,
    NOTHING_TO_RECEIVE,
    NOTHING_TO_DISPATCH,
    EMPTY_BARCODE,
    PURCHASE_ORDER_NOT_FOUND,
    SALES_ORDER_NOT_FOUND,
    NO_COMPANY_CONFIGURED,
    NETWORK_UNREACHABLE,
    NETWORK_DNS,
    NETWORK_TIMEOUT,
    NETWORK_TLS,
    NO_SERVER_CONFIGURED,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    BAD_REQUEST,
    SERVER_ERROR,
    SERVER_UNAVAILABLE,
    INVALID_RESPONSE,
    OVER_PICK,
    PICKING_INCOMPLETE,
    PICKING_NOT_STARTED,
    PICKING_NOT_COMPLETED,
    PICK_LIST_ALREADY_PICKED,
    PICK_LIST_NOT_FOUND,
    UNSUPPORTED_PICK_PURPOSE,
    UNKNOWN,
}

/**
 * Domain-level error taxonomy. The data layer maps transport/ERPNext errors into one of these
 * so that ViewModels never depend on HTTP or Retrofit types.
 *
 * [code] is set for errors generated by the app (localizable); it is null when [message] is a
 * free-text message coming from the ERPNext server.
 */
sealed class AppError(
    open val message: String,
    open val code: ErrorCode?,
    open val args: List<String>,
) {
    /** Could not reach the server (DNS, timeout, TLS, offline...). */
    data class Network(
        override val message: String = "Unable to reach the ERPNext server",
        override val code: ErrorCode? = ErrorCode.NETWORK_UNREACHABLE,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)

    /** Invalid credentials or the session has expired. */
    data class Unauthorized(
        override val message: String = "Invalid credentials or session expired",
        override val code: ErrorCode? = ErrorCode.UNAUTHORIZED,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)

    /** The user is authenticated but lacks the ERPNext role/permission. */
    data class Forbidden(
        override val message: String = "You do not have permission for this action",
        override val code: ErrorCode? = ErrorCode.FORBIDDEN,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)

    /** The requested document does not exist. */
    data class NotFound(
        override val message: String = "Not found",
        override val code: ErrorCode? = ErrorCode.NOT_FOUND,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)

    /** Input validation failed either locally or on the server (e.g. ValidationError). */
    data class Validation(
        override val message: String,
        override val code: ErrorCode? = null,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)

    /** ERPNext returned a server side failure. */
    data class Server(
        override val message: String,
        val httpCode: Int? = null,
        override val code: ErrorCode? = null,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)

    /** Anything that could not be classified. */
    data class Unknown(
        override val message: String = "Something went wrong",
        override val code: ErrorCode? = ErrorCode.UNKNOWN,
        override val args: List<String> = emptyList(),
    ) : AppError(message, code, args)
}
